### ISSUE TITLE
Does not detect optional starting arg properly

### ISSUE THREAD

**Issue by Stanzilla** [Kampfkarren/selene#137]
The function has an optional starting as, see https://wow.gamepedia.com/API_hooksecurefunc but I don't see a way for tell Selene about that.

Code:

```lua
hooksecurefunc("ChatEdit_InsertLink", function(...) return _G.AceGUIWeakAurasMultiLineEditBoxInsertLink(...) end)
```

Config:

```toml
[[hooksecurefunc.args]]
type = "table"
required = false
[[hooksecurefunc.args]]
type = "string"
[[hooksecurefunc.args]]
type = "function"
```

Error: 

```
error[incorrect_standard_library_use]: use of standard_library function hooksecurefunc is incorrect

    ┌── WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasMultiLineEditBox.lua:21:41 ───
    │
 21 │   hooksecurefunc("ChatEdit_InsertLink", function(...) return _G.AceGUIWeakAurasMultiLineEditBoxInsertLink(...) end)
    │                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected string, received function
```
