### ISSUE TITLE
Support `goto` statements.

### ISSUE THREAD

**Issue by howmanysmall** [Kampfkarren/selene#224]
Currently Selene doesn't really like my usage of `goto` labels, as shown below. It'd be nice if it was supported.
![image](https://user-images.githubusercontent.com/26746527/112914175-88e4a480-90b8-11eb-975b-f2ba23d59872.png)

**Comment by Kampfkarren** [comment]
Relies on a full-moon update.

**Comment by Kampfkarren** [comment]
#229 makes this possible, though a separate PR will need to turn on lua52 feature flag.

**Comment by esatterwhite** [comment]
@Kampfkarren I'm still getting this error on 0.24.0 w/ `lua52` as a base.
Is there something special that needs to be done to enable this support?

**Comment by Kampfkarren** [comment]
It's more viable today than when this issue was first posted though

**Comment by esatterwhite** [comment]
I'd have to build one my self? do you have an example build command for this?

**Comment by Kampfkarren** [comment]
You would need to edit Cargo.toml in selene to include lua52 for full-moon

**Comment by esatterwhite** [comment]
ok. that seems to have worked. I'm not sure its entirely right.

```toml
# Cargo.toml

[workspace.dependencies]
full_moon = { version = "0.17.0", features = ["lua52"] }
```

```toml
#selene/Cargo.toml

[features]
default = [ "roblox", "lua52" ]
lua52 = []
tracy-profiling = ["profiling/profile-with-tracy","tracy-client"]
roblox = ["selene-lib/roblox", "full_moon/roblox", "ureq"]
```
