### ISSUE TITLE
prettier for selene-vscode

### ISSUE THREAD

**Issue by Kampfkarren** [Kampfkarren/selene#253]
.prettierrc.toml:

```toml
semi = false
tabWidth = 4
trailingComma = "all"
```

Put it on CI as well.
