### ISSUE TITLE
Roblox std does not include Enum:GetEnums()

### ISSUE THREAD

**Issue by LouieK22** [Kampfkarren/selene#312]
Selene marks ``Enum:GetEnums()`` as an non-existent class even though it exists. https://developer.roblox.com/en-us/api-reference/datatype/Enums

Current workaround:
```toml
[selene]
base = "roblox"
name = "custom"

[Enum.GetEnums]
method = true
args = []
```
