### ISSUE TITLE
Roblox Standard Library EnumItem has no Value

### ISSUE THREAD

**Issue by LastTalon** [Kampfkarren/selene#372]
When using attempting to use the `Value` property of an `EnumItem` selene complains that this is incorrect standard library usage.

This happens when attempting to use something like `Enum.ContextActionPriority.High.Value`. The `EnumItem` in the Roblox standard library definition appears to define `Value` when I checked, and it says the same thing whether `roblox.yml` exists or not.

**Comment by Kampfkarren** [comment]
Yikes. Either something is wrong with structs, or I misunderstood them, but this should be working.

![image](https://user-images.githubusercontent.com/3190756/173170427-1755b022-d971-4ff5-b3c5-f30d29be77fb.png)

**Comment by Kampfkarren** [comment]
Hmm, worse that seems to work in an independent test.

**Comment by Kampfkarren** [comment]
Compressed into this MVCE:

```yml
---
globals:
  Enum:
    struct: Enum
  Enum.ABTestLoadingStatus.Error:
    struct: EnumItem
structs:
  Enum:
    GetEnumItems:
      args: []
      method: true
  EnumItem:
    Value:
      property: read-only
```
