### ISSUE TITLE
You cannot mix structs with other forms of indexing

### ISSUE THREAD

**Issue by Kampfkarren** [Kampfkarren/selene#374]
Root of #372.

The following standard library:

```yml
---
globals:
  Enum:
    struct: Enum
  Enum.ABTestLoadingStatus.Error:
    struct: EnumItem
structs:
  Enum:
    GetEnumItems:
      args: []
      method: true
  EnumItem:
    Value:
      property: read-only
```

...does not support `Enum.ABTestLoadingStatus.Error`, because it sees it is not explicitly defined, then goes through `Enum`, sees its a struct, and follows that path, to get to a dead end.
