### ISSUE TITLE
Include arbitrary field support to standard library globals

### ISSUE THREAD

**Issue by Kampfkarren** [Kampfkarren/selene#416]
Good for plugins.

Something like:

```yml
---
globals:
  foo:
    any: true
    extra:
      fielda: 1
```
