### ISSUE TITLE
Lua 5.3 STD string.pack incorrect signature

### ISSUE THREAD

**Issue by checkraisefold** [Kampfkarren/selene#499]
The current signature for string.pack in the default Lua 5.3 STD is:
```yaml
  string.pack:
    args:
      - type: string
    must_use: true
```
The correct signature, which is correct in the Luau STD, is:
```yaml
  string.pack:
    args:
      - type: string
      - type: ...
    must_use: true
```

The same issue exists with string.unpack. This issue causes any usage of these functions that actually works to throw a selene warning, considering the function requires 2 arguments to work.
