### ISSUE TITLE
Selene reports ternary operators as bools

### ISSUE THREAD

**Issue by howmanysmall** [Kampfkarren/selene#51]
The configuration I have setup is as follow.
```toml
[[table.unpack.args]]
type = "table"

[[table.unpack.args]]
type = "number"
required = false

[[table.unpack.args]]
type = "number"
required = false
```

And this is the error I get, with context.
![image](https://user-images.githubusercontent.com/26746527/69191475-cb1ece80-0adf-11ea-830b-88927bdf148e.png)
