### ISSUE TITLE
[Feature request] std globals aliases

### ISSUE THREAD

**Issue by Commandcracker** [Kampfkarren/selene#527]
## Description

std globals aliases would make writing a std faster.

## Example:
```yml
    assert.error:
        args:
            - type: function
            - type: string
              required: false
    assert.Error:
        args:
            - type: function
            - type: string
              required: false
    assert.has_error:
        args:
            - type: function
            - type: string
              required: false
    assert.no_error:
        args:
            - type: function
            - type: string
              required: false
    assert.no_has_error:
        args:
            - type: function
            - type: string
              required: false
    assert.has_no_error:
        args:
            - type: function
            - type: string
              required: false
```
↓
```yml
    assert.error:
        args:
            - type: function
            - type: string
              required: false
        aliases:
            - assert.Error
            - assert.has_error
            - assert.no_error
            - assert.no_has_error
            - assert.has_no_error
```
