### ISSUE TITLE
Specify message passed to standard library format for standard_library missing required parameter

### ISSUE THREAD

**Issue by chriscerie** [Kampfkarren/selene#544]
With standard library format:
```yml
assert:
  args:
    - type: any
    - required: A failed assertion without a message is unhelpful to users.
      type: string
```

Currently if user specifies only one arg:
```
error[incorrect_standard_library_use]: standard library function `assert` requires 2 parameters, 1 passed
  ┌─ assert.lua:6:1
  │
6 │ assert(true)
  │ ^^^^^^^^^^^^
  │
  ```
This has been the source of confusion for many as the 2nd `assert` parameter is technically optional, but selene chooses to enforce it as required since the default assert error is unhelpful. The current selene error doesn't specify that, so the message in the standard library format should be added as a note.

Another example of this is with `error` to ensure solution is generic:
```yml
error:
  args:
    - required: Erroring without a message is unhelpful to users.
      type: string
    - required: false
      type: number
```
