### ISSUE TITLE
expected `"function"`, received `function`

### ISSUE THREAD

**Issue by kasper93** [Kampfkarren/selene#598]
```
error[incorrect_standard_library_use]: use of standard_library function `mp.add_key_binding` is incorrect
     ┌─ player/lua/osc.lua:2974:20
     │
2974 │ mp.add_key_binding(nil, "visibility", function() visibility_mode("cycle") end)
     │                    ^^^ expected `"nil", "string"`, received `nil`
```
```
error[incorrect_standard_library_use]: use of standard_library function `mp.add_key_binding` is incorrect
     ┌─ player/lua/osc.lua:2974:39
     │
2974 │ mp.add_key_binding(nil, "visibility", function() visibility_mode("cycle") end)
     │                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `"function"`, received `function`

```

```
  mp.add_key_binding:
    args:
      - type:
          - nil
          - string
        observes: read
      - type:
          - function
          - string
        observes: read
      - type:
          - function
        observes: read
        required: false
      - type:
          - table
        observes: read
        required: false
```
