### ISSUE TITLE
goto invalid with Lua 5.2

### ISSUE THREAD

**Issue by EddieEldridge** [Kampfkarren/selene#620]
**selene.toml**
```toml
# Selene Linter
# https://github.com/Kampfkarren/selene
std = "M2TWEOP"
exclude = [
"3rd/*", 
"redist/*", 
"helpers/mobdebug.lua", 
"helpers/inspect.lua", 
"helpers/tableSave.lua",
"helpers/profiler.lua",
"helpers/dkjson.lua",
"helpers/Scratchpad.lua",
"LuaDocs.lua",
"LuaImGuiDocs.lua",
]

[lints]
unscoped_variables = "allow"
multiple_statements = "allow"
undefined_variable = "allow"
unused_variable = "allow"
parenthese_conditions = "allow"
if_same_then_else = "allow"
```

**M2TWEOP.yml**
```yml
---
base: lua52
name: M2TWEOP
```

```shell
ago-beta/eopData/eopScripts on  master [!] via 🌙 v5.4.6
❯ selene .
error[parse_error]: unexpected token `goto`
   ┌─ Campaign/garrisons.lua:19:104
   │
19 │                 if faction.factionID == F_KHAZAD.id and not IsFactionAIControlled(F_GOBLINS.name) then goto skipspawn end
   │                                                                                                        ^^^^ expected 'end'

error[parse_error]: unexpected token `goto`
   ┌─ Campaign/randomGenerator.lua:98:21
   │
98 │                     goto found
   │                     ^^^^ expected 'end'

Results:
0 errors
0 warnings
2 parse errors

ago-beta/eopData/eopScripts on  master [!] via 🌙 v5.4.6
❯ selene --version
selene 0.27.1
```

Just a little bit confused as to why this is an error? 🤔 I get the same thing with lua53 as the base. Thanks and cool project.
