### ISSUE TITLE
Unclear Documentation

### ISSUE THREAD

**Issue by Stanzilla** [Kampfkarren/selene#90]
I saw people use 

```toml
empty_if = { comments_count = false }
unused_variable = { allow_unused_self = true }
```

in their config but the CLI complains about it being wrong, what's the correct format? The docs have no example...

**Comment by Kampfkarren** [comment]
This is explained in the documentation. You need to put `[config]` over these.

https://kampfkarren.github.io/selene/cli/configuration.html#configuring-specific-rules

**Comment by Stanzilla** [comment]
Oh I had it in [rules], my bad, sorry!

**Comment by Stanzilla** [comment]
What's the structure for defining globals then?

```toml
[globals]
LibStub = true
```

and 

```
```toml
[globals]
[LibStub]
any = true
```

both still trigger

```
error[undefined_variable]: `LibStub` is not defined

    ┌── WeakAuras/Libs/AceConfig-3.0/AceConfigCmd-3.0/AceConfigCmd-3.0.lua:20:22 ───
    │
 20 │ local AceConfigCmd = LibStub:NewLibrary(MAJOR, MINOR)
```

**Comment by Kampfkarren** [comment]
You're meant to create a separate TOML file for standard libraries and reference it in selene.toml with `std = "filename"`

**Comment by Stanzilla** [comment]
Okay is there a way to do something like this

```toml
[C_Scenario]
	properties:
		GetBonusStepRewardQuestID = true
		GetBonusSteps = true
		GetCriteriaInfo = true
		GetCriteriaInfoByStep = true
		GetInfo = true
		GetProvingGroundsInfo = true
		GetScenarioIconInfo = true
		GetStepInfo = true
		GetSupersededObjectives = true
		IsInScenario = true
		ShouldShowCriteria = true
		TreatScenarioAsDungeon = true
```

Instead of having to do

```toml
[C_Scenario.GetBonusStepRewardQuestID]
property = true
```

for every function of the namespace that I want to whitelist?
